### ISSUE TITLE
ykval_verifier SQL user doesn't have permission to INSERT INTO clients, breaks ykval-gen-clients

### ISSUE THREAD

**Issue by mig5** [Yubico/yubikey-val#20]
Trying to follow the instructions at 'GeneratingClients' here: https://github.com/Yubico/yubikey-val/wiki/GeneratingClients

I run: ykval-gen-clients --urandom 11

But there is no output. Instead ykval.log shows:

>LOG_DEBUG:ykval-gen-clients:db:DB query is:SELECT id FROM clients ORDER BY id DESC LIMIT 1
>LOG_DEBUG:ykval-gen-clients:db:DB query is: INSERT INTO clients (id,active,created,secret,email,notes,otp) VALUES ('1', '1', '1404359826','XXXXXXXXXXXXXXXXXXXXXXXX =','','','')
>LOG_INFO:ykval-gen-clients:db:Database query error: Array (     [0] => 42000     [1] => 1142     [2] => INSERT command denied to user 'ykval_verifier'@'localhost' for table 'clients' )
>LOG_ERR:ykval-gen-clients:Failed to insert new client with query INSERT INTO clients (id,active,created,secret,email,notes,otp) VALUES ('1', '1', '1404359826’,’XXXXXXXXXXXXXXXXXXXXXXXX=','','','')
>Failed to insert new client with query INSERT INTO clients (id,active,created,secret,email,notes,otp) VALUES ('1', '1', '1404359826','XXXXXXXXXXXXXXXXXXXXXXXX =','','','')`

It looks like the instructions should grant INSERT privileges to the 'clients' table, would you agree?

Currently it says:

`GRANT SELECT(id, secret, active) ON ykval.clients TO 'ykval_verifier'@'localhost'; \`

**Comment by paulmenzel** [comment]
Hi. I hit the same problem and it’s also reported in [*Building a local Yubikey server infrastructure*](http://www.kilala.nl/index.php?id=2340).

> More tweaks are needed once you are finished:
> […]
> * Change the access rights for account ykval_verifiver in the YKVAL database. By default it cannot write into the ykval_clients table, which is needed to register new clients. Run: GRANT ALL PRIVILEGES ON ykval_clients TO ‘ykval_verifier’@‘localhost’; FLUSH PRIVILEGES;

Yubico, would you like mig5 or me to send a request to update the documentation?

Or is there a reason, why no insert privileges should be granted?
