### ISSUE TITLE
Ubuntu server 14.04

### ISSUE THREAD

**Issue by hechacker1** [Yubico/yubikey-val#27]
I just wanted to point out that for a2ensite to work, the apache config files need to have a .conf extension for a2ensite to pick it up:

root@yubikey-val:/var/www# cd /etc/apache2/sites-available/
root@yubikey-val:/etc/apache2/sites-available# mv ykval ykval.conf
root@yubikey-val:/etc/apache2/sites-available# mv ykval-ssl ykval-ssl.conf
root@yubikey-val:/etc/apache2/sites-available# a2ensite ykval
Enabling site ykval.
To activate the new configuration, you need to run:
  service apache2 reload

Otherwise, it looks like the documentation is still relevant. Thanks

**Comment by minisu** [comment]
Thanks, I updated the docs (90b876a4055aa0efc30e1549516c01ab66db10a9)! Not sure why this issue hasn't been dealt with earlier.
