### ISSUE TITLE
recent commit breaks existing installations with BAD_OTP

### ISSUE THREAD

**Issue by highcourter** [Yubico/yubikey-val#32]
in commit 382cfc2 the default URL for ykval got a port 8002. This breaks our installation:

we did install before the patch according to the gudie (https://github.com/Yubico/yubix/blob/master/doc/Getting_Started.adoc). After doing upgrade to latest version the response of OTP validation is BAD_OTP. The URL was changed without adopting the apache2 config (it's simply not listening on 8002).
For us that was critical - maybe it could have supported still port 80 and 8002? Or is there a place to get noted of such significant changes maybe which we miss?

Thx in advance for any info about this issue

**Comment by dainnilsson** [comment]
Hi, sorry about that, that was an oversight on our part. We've pushed a new commit to fix this (c4b20dd1), and will be publishing a new release with it shortly.

**Comment by jeanpaulgalea** [comment]
Hi, sorry about the inconvenience, that change should have been included in the release news.

I have made a new release now, which includes https://github.com/Yubico/yubikey-val/commit/c4b20dd1059530a4ecf9ecc21a60b327dc5e43b1 among other changes.

**Comment by highcourter** [comment]
@jeanpaulgalea: waiting on the ppa upstream (trusty) now - but already thank you very much for this fast reaction & fix!

**Comment by jeanpaulgalea** [comment]
@highcourter should be on its way now! My colleague @klali is pushing that through as we speak.

**Comment by highcourter** [comment]
tested and got the additional line, great!
