### ISSUE TITLE
yk_publicname in ykval-synclib.php

### ISSUE THREAD

**Issue by bmwt** [Yubico/yubikey-val#41]
having issues with ykval-queue processing- specifically, something in ykval-synclib.php is not properly passing yk_publicname, causing a bad (null) entry in the yubikeys table. (the "searching for yk_publicname  in local db" line)

debug info:

LOG_DEBUG:ykval-queue:synclib:response contains  modified=1461770674 nonce=ihbygicyzcpxrdsattfetzcnocnlvfmg yk_publicname=ccccccddnrki yk_counter=229 yk_use=0 yk_high=21 yk_low=49226
LOG_DEBUG:ykval-queue:synclib:db:DB query is: UPDATE yubikeys SET  modified='1461770674', yk_counter='229', yk_use='0', yk_low='49226', yk_high='21', nonce='ihbygicyzcpxrdsattfetzcnocnlvfmg' WHERE yk_publicname = 'ccccccddnrki' and (229>yk_counter or (229=yk_counter and 0>yk_use))
LOG_INFO:ykval-queue:synclib:database not updated modified=1461770674 nonce=ihbygicyzcpxrdsattfetzcnocnlvfmg yk_publicname=ccccccddnrki yk_counter=229 yk_use=0 yk_high=21 yk_low=49226
LOG_DEBUG:ykval-queue:synclib:searching for yk_publicname  in local db
LOG_DEBUG:ykval-queue:synclib:db:DB query is: SELECT * FROM yubikeys WHERE yk_publicname is NULL LIMIT 1
LOG_NOTICE:ykval-queue:synclib:Discovered new identity 
LOG_DEBUG:ykval-queue:synclib:db:DB query is: INSERT INTO yubikeys (active,created,modified,yk_counter,yk_use,yk_low,yk_high,nonce,notes) VALUES ('1','1461780090','-1','-1','-1','-1','-1','0000000000000000','')
LOG_DEBUG:ykval-queue:synclib:db:DB query is: SELECT * FROM yubikeys WHERE yk_publicname is NULL LIMIT 1
LOG_NOTICE:ykval-queue:synclib:params for yk_publicname  not found in database
LOG_DEBUG:ykval-queue:synclib:validation params:  modified= nonce= yk_publicname= yk_counter= yk_use= yk_high= yk_low=
LOG_DEBUG:ykval-queue:synclib:OTP params: 
LOG_NOTICE:ykval-queue:synclib:Local server out of sync compared to counters at validation request time. 
LOG_WARNING:ykval-queue:synclib:Local server out of sync compared to current local counters. Local server updated. 
LOG_ERR:ykval-queue:synclib:Remote server has higher counters than OTP. This response would have marked the OTP as invalid. 
LOG_DEBUG:ykval-queue:synclib:deleting queue entry with modified= server_nonce= server=
LOG_DEBUG:ykval-queue:synclib:db:DB query is: DELETE FROM queue WHERE modified = '' and server_nonce = '' and server = ''

**Comment by klali** [comment]
With what version of yubikey-val is this? 2.35?
What version of php and curl is this running with?

What probably happens here is that something goes wrong with using the CURLINFO_PRIVATE storage at https://github.com/Yubico/yubikey-val/blob/master/ykval-synclib.php#L331

**Comment by klali** [comment]
And for that matter, is there a LOG_DEBUG line just above starting "handle indicated to be for"... ?

**Comment by bmwt** [comment]
LOG_DEBUG:ykval-queue:synclib:YK-VAL resync adding URL : http://dev-rad.es.net/wsapi/2.0/sync?otp=ccccccddnrkijcktikdlrvlbkreglkvbdehibfbcfdhf&modified=1461701994&yk_publicname=ccccccddnrki&yk_counter=221&yk_use=0&yk_high=73&yk_low=47638&nonce=viesoftpbgyhpkjgtpzuksaxxdktjjge
LOG_DEBUG:ykval-queue:synclib:handle indicated to be for .


curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2

PHP 5.3.3 (cli) (built: Feb  9 2016 10:36:17)

**Comment by klali** [comment]
a very quick guess at what's going on is in the branch sync-fixup could you try to run with ykval-synclib.php from that?

**Comment by bmwt** [comment]
that did it- the branch sync-fixup works much better, and we can see the updates propagating.  We still see:
PHP Warning:  curl_close() expects parameter 1 to be resource, array given in /usr/share/yubikey-val/ykval-synclib.php on line 446 

inside the /usr/sbin/ykval-queue script, but that doesn't seem to be fatal.

our redundancy project can move forward- thanks!

**Comment by klali** [comment]
Very good, thank you for testing!

That branch is now merged and the next release will include that fix.
