### ISSUE TITLE
One step not covered in any of the documentation..

### ISSUE THREAD

**Issue by zxcvbn4038** [Yubico/yubikey-val#44]
There is one step not covered in any of the documentation, that I could find, how do I setup a key to use this?

I have a Yubikey NEO that my employer gave me, there is a tiny barcode and a six digit number printed on the back, when I push its button it "types" an eight digit number. What would I need to do to use it with the validator?

**Comment by klali** [comment]
This component needs to run together with a ksm component that is what actually holds the keys, either https://developers.yubico.com/yubikey-ksm/ or https://developers.yubico.com/python-pyhsm/

If your key prints an 8 digit code that is an 8 digit HOTP code, that can't be used together with these projects. The key has two slots though and can be reprogrammed and after that used with a Yubico OTP validation server. https://developers.yubico.com/yubikey-manager-qt/ is a tool that can be used for reprogramming the key.
