### ISSUE TITLE
Verification output (1): Yubikey OTP was bad (BAD_OTP)

### ISSUE THREAD

**Issue by sarlacpit** [Yubico/yubikey-val#47]
Hi guys,

I am using freeRADIUS with a local KSM & Validation server for OTP authentication. Though after ruling out Radius

I am sure this is a configuration error, but I have been going around in circles for a week and getting nowhere so I am starting to think its an issue with my local valuation server where as it is not verifying the OTP.

I have a working version running on Ubuntu 12.04 and I am trying a fresh install on Ubuntu 16.04  so I am sure my config is right but could be room for error. 

```

ykclient --debug --url "https://localhost/wsapi/2.0/verify?id=%d&otp=%s" --apikey  9uhj+B7nlkYwXL2NhKSbJ6hxj4= 2 aaaaaaaaaaafijfbvukgvluvvgnirkhcrgjubuebihn

Input:
  validation URL: https://localhost/wsapi/2.0/verify?id=%d&otp=%s
  client id: 2
  token: aaaaaaaaaaafijfbvukgvluvvgnirkhcrgjubuebihn
  api key: m9uhj+B7nlkYwXL2NhKSbJ6hxj4=
Response from: https://localhost/wsapi/2.0/verify?id=2&nonce=pusktrsfbqlgctysakuigxsxktaerzyj&otp=aaaaaaaaaaafijfbvukgvluvvgnirkhcrgjubuebihn&h=%2FAKOLOM6mKRLvJZ2InJlRmv%2Bx%2FM%3D
Verification output (1): Yubikey OTP was bad (BAD_OTP)
  otp: (null)
  nonce: (null)
  t: 2017-12-01T16:59:22Z0699
  timestamp: (null)
  sessioncounter: (null)
  sessionuse: (null)
  sl: (null)
  status: BAD_OTP

```

My log files shows a similar error:

```
 LOG_DEBUG:ykval-verify:[::1] [aaaaaaaaaaafijfbvukgvluvvgnirkhcrgjubuebihn] SIGN: stat
us=BAD_OTP&t=2017-12-01T16:59:22Z0699 H=u3SsG2c+9RTaulI5v+pnJcHNDzQ=
LOG_DEBUG:ykval-verify:[::1] [aaaaaaaaaaafijfbvukgvluvvgnirkhcrgjubuebihn] SIGN: stat
us=BAD_OTP&t=2017-12-01T16:59:22Z0699 H=u3SsG2c+9RTaulI5v+pnJcHNDzQ=
```

Probably not a bug but I'd appreciate any debugging tips.

Thanks in advance

**Comment by klali** [comment]
The otp you have there (aaaaaaaaaaafijfbvukgvluvvgnirkhcrgjubuebihn) contains invalid characters. You should have more log output though.

You might also want to be more careful with your apikey, you should make sure to change that before you move into production with this.

**Comment by sarlacpit** [comment]
Hi Klali,

Thanks for your reply. I edited the api key and the yubikey output for the post, my Yubikey produces 45 chars not 44 thats a typo - is that what you meant by invalid characters?

Thanks

**Comment by klali** [comment]
Ok, the a in your OTP is not a valid character for modhex, but I assume you edited that then?

It looks like you have a ksm error, what do you get if you visit the ksm url (https://localhost:443/wsapi/decrypt?otp=aaaaaaaaaaaadrlcubevcebjndkiubfvhtfjufdhjeil) reported manually?
Might it be that ssl validation fails for that name with the key and cert used?
Do you get any logging from your ksm?

**Comment by sarlacpit** [comment]
Thanks again for your reply, yes, I had edited to include the 'a'.

I have just tried performing a curl on the url and I'm actually getting error 404... Which is interesting as my document root in Apache2 is a valid one:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /wsapi/decrypt was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at localhost Port 443</address>
</body></html>
```
Relevent apache conf:

```
<VirtualHost localhost:443>
        ServerAdmin webmaster@localhost
        ServerName localhost

        DocumentRoot /var/www/
        <Directory />
```
Directory details...

```
ls -alh /var/www/wsapi
drwxr-xr-x 2 root root 4.0K Dec  4 11:41 .
drwxr-xr-x 4 root root 4.0K Dec  4 12:09 ..
lrwxrwxrwx 1 root root   40 Dec  4 11:41 decrypt.php -> /usr/share/yubikey-ksm/ykksm-decrypt.php
lrwxrwxrwx 1 root root   32 Dec  4 11:41 .htaccess -> /usr/share/yubikey-ksm/.htaccess

```

Is there any special considerations I have missed, I have tried changing the ownership of the decrypt.php which didn't work, Ubuntu 16.04 uses php7.0 by default, could this make a difference?

Thanks again.

**Comment by sarlacpit** [comment]
Actually... I have just revisited the SSL cert... Looks like there is some issue with it and it is trying to use http.

```

*   Trying ::1...
* Connected to localhost (::1) port 443 (#0)
* found 174 certificates in /etc/ssl/certs/ca-certificates.crt
* found 630 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: localhost (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=GB,ST=Somewhere,O=Not Ltd Ltd,CN=localhost
* 	 start date: Tue, 05 Jul 2016 09:05:00 GMT
* 	 expire date: Sun, 04 Jul 2021 09:05:00 GMT
* 	 issuer: C=GB,ST=Somewhere,O=Not Ltd
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /wsapi/decrypt?otp=cccccccccccebrhhutjghffjtbfivgegrjktdcbfjbll HTTP/1.1
> Host: localhost
> User-Agent: curl/7.47.0
> Accept: */*

```

I'll have another look at it and report back my findings. 

Thanks again.

**Comment by klali** [comment]
You're also asking for decrypt, but the file is named decrypt.php you probably need to alias it or similar.

**Comment by sarlacpit** [comment]
Just to rule SSL out I have reconfigured Apache2 to us port 80 and use decrypt.php. 
The error has now changed. I am now getting a permissions issue, however having changed the permissions to allow www-data on 775 in /var/www/* i am still getting the issue.

I wonder if there is something specific to php7.0.

```
> *   Trying ::1...
> * Connected to localhost (::1) port 80 (#0)
> > GET /wsapi/decrypt.php?otp=aaaaaaaaaaaaactuujuihulccltejlijniuckbjrvlkvb HTTP/1.1
> > Host: localhost
> > User-Agent: curl/7.47.0
> > Accept: */*
> > 
> * HTTP 1.0, assume close after body
> < HTTP/1.0 500 Internal Server Error
> < Date: Mon, 04 Dec 2017 14:29:25 GMT
> < Server: Apache/2.4.18 (Ubuntu)
> < Content-Length: 0
> < Connection: close
> < Content-Type: text/html; charset=UTF-8
> < 
> * Closing connection 0
> [Mon Dec 04 14:29:25.822425 2017] [:error] [pid 3884] [client ::1:36838] PHP Warning:  Unknown: failed to open stream: Permission denied in Unknown on line 0
> [Mon Dec 04 14:29:25.822472 2017] [:error] [pid 3884] [client ::1:36838] PHP Fatal error:  Unknown: Failed opening required '/var/www/wsapi/decrypt.php' (include_path='/etc/yubico/ksm:/usr/share/yubikey-ksm') in Unknown on line 0
```

**Comment by klali** [comment]
Since it's a symlink make sure you have appropriate permissions on /usr/share/yubikey-ksm/ykksm-decrypt.php and other files in that directory.

**Comment by sarlacpit** [comment]
Thanks, that seems to have fixed it. I had a few other issues including changing /etc/yubico/val/ykval-config.php to reflect the correct url path. 

Thanks for your assistance in what seems to be a few schoolboy errors.
