### ISSUE TITLE
ykclient return value (109): Error performing curl

### ISSUE THREAD

**Issue by nydevnet** [Yubico/yubikey-val#58]
FreeRADIUS, PAM and Yubikeys have been working fine for the past year.
This morning though my users have experienced the following errors when trying to use the OTP.
Nothing has changed on the server that I can see in the logs over the weekend. 

```debug: pam_yubico.c:1154 (pam_sm_authenticate): Token is associated to the user. Validating the OTP...
debug: pam_yubico.c:1156 (pam_sm_authenticate): ykclient return value (109): Error performing curl
debug: pam_yubico.c:1157 (pam_sm_authenticate): ykclient url used: 
debug: pam_yubico.c:1220 (pam_sm_authenticate): done. [Authentication service cannot retrieve authentication info]
Mon Feb 10 14:41:34 2020 : Debug: pam_pass: function pam_authenticate FAILED for <user.name>. Reason: Authentication service cannot retrieve authentication info
Mon Feb 10 14:41:34 2020 : Info: ++[pam] = reject
```

This is my versioning - Ubuntu 16.04:

```yubikey-ksm                  1.15-4ubuntu1       all
yubikey-val                  2.39-2~ppa1~xenial1 all
```

I'm a bit lost as to why it would fail. The server logs shows many itterations of:

```Feb  9 07:02:18 radius1 ykval[978]: LOG_DEBUG:ykval-queue:synclib:starting resync
Feb  9 07:02:18 radius1 ykval[978]: LOG_DEBUG:ykval-queue:synclib:db:DB query is: select distinct server from queue WHERE queued < 1581231728 or queued is null
```
Apache2 is running and reachable
MYSQL is running and reachable 

Any ideas?

Thanks

**Comment by nevun** [comment]
What does your pam conf look like? Which linux and package versions on the client?

`ykclient url used: ` looks pretty weird, no URL at all? Which endpoints are you using?

**Comment by nydevnet** [comment]
Thank you for your reply.

I am using Ubuntu 16.04.6 LTS - with kernel: 4.4.0-173-generic.
The server is on premise, as well as the databases which are local to the Radius server.

Here's the packages
```
dpkg --list | grep yubi
ii  libpam-yubico                          2.26-1~ppa1~xenial1                             amd64        two-factor password and YubiKey OTP PAM module
ii  libyubikey0                            1.13-1                                          amd64        Yubikey OTP handling library runtime
ii  yubikey-ksm                            1.15-4ubuntu1                                   all          Key Storage Module for YubiKey One-Time Password (OTP) tokens
ii  yubikey-val                            2.39-2~ppa1~xenial1                             all          One-Time Password (OTP) validation server for YubiKey tokens

```
The Pam config:
```
auth requisite pam_yubico.so id=1 [redacted]= debug authfile=/etc/yubikey_mapping urllist=https://localhost/wsapi/2.0/verify mode=client
auth required /lib/security/pam_mysql.so user=[redacted] passwd=[redacted] host=localhost db=radius table=radcheck usercolumn=UserName passwdcolumn=Value crypt=1
account required /lib/security/pam_mysql.so user=[redacted] passwd=[redacted] host=localhost db=radius table=radcheck usercolumn=UserName passwdcolumn=Value crypt=1
```

It gets weird as nothing has changed on the server and i can authenticate to the databases using the  /etc/yubico/val and  /etc/yubico/ksm config files.

**Comment by nevun** [comment]
`urllist=https://localhost/wsapi/2.0/verify`

expired cert? can you connect to it with curl and validate an OTP?

**Comment by nydevnet** [comment]
The cert is loos valid

```cat ca-certificates.crt | openssl x509 -noout -dates
notBefore=Jul  5 09:05:00 2016 GMT
notAfter=Jul  4 09:05:00 2021 GMT
```

> can you connect to it with curl and validate an OTP?

Sorry, I'm not too sure how to do that but i do get an error using https.

`curl https://localhost/wsapi/verify?otp=[redacted]`
`curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`

If i bypass the SSL check using curl -k i get:

```t=2020-02-11T10:57:49Z0218
status=MISSING_PARAMETER
```
Which would seem right... So where has my CRL file gone?

**Comment by nevun** [comment]
You seem to have all you need to fix this now. I do not think this is relevant to ykclient since it is curl that is failing and ykclient is using curl. Feel free to re-open if you disagree.

**Comment by nydevnet** [comment]
Confirmed, it is a certificate issue. I have bypassed https in the pam config and yubikeys are working once again.

I suspect I will need to regenerate my CA. Is there anything gotchas I'll need to watch out for? 

Thanks for your help,
